import { MethodologyVersion } from '../types';

export const BM_EN01_001: MethodologyVersion = {
  code: 'BM EN01.001',
  name: 'Grid-connected electricity generation from renewable sources',
  type: 'REAL_AUTHORITATIVE_METHODOLOGY',
  version: '1.0',
  sector: 'Renewable Energy',
  sectoralScopeCode: '01: Energy',
  publicationDate: '27 March 2025',
  effectiveDate: '27 March 2025',
  issuingAuthority: 'Bureau of Energy Efficiency (BEE), Ministry of Power, Government of India',
  referenceUnfcccCdm: ['ACM0002 (as valid from 31 May 2024)'],
  pageCount: 28,
  sourceUrl: 'https://beeindia.gov.in',
  sourceDocument: 'BM_EN01_001_Grid_Connected_Renewable.pdf',
  documentHash: 'd9d849e0d748cff356da983c869853df2cd92add3107334bbbda873d09234ff1',
  retrievalDate: '2026-08-29',
  isActive: true,
  isSynthetic: false,
  verificationStatus: 'VERIFIED',
  description: 'Applies to grid-connected renewable energy generation project activities that include construction and operation of a Greenfield power plant, or retrofitting, rehabilitation, replacement or capacity addition of an existing power plant. Also applies to grid-connected renewable energy integrating Battery Energy Storage Systems (BESS) or Pumped Storage Projects (PSP).',
  adoptedTools: [
    'BM-T-001: Combined tool to identify the baseline scenario and demonstrate additionality',
    'BM-T-002: Tool to calculate project or leakage CO2 emissions from fossil fuel combustion',
    'BM-T-003: Baseline, project and/or leakage emissions from electricity consumption and monitoring of electricity generation',
    'BM-T-012: Positive lists of technologies'
  ],
  externalDependencies: [
    {
      title: 'CEA CO2 Baseline Database',
      exactWording: 'Grid Emission Factor (for net effective injection into grid) for grid connected power generation in year y, as published by the CEA',
      section: '4.5, paragraph 49 / 66',
      page: 18,
      paragraph: '49',
      impact: 'Baseline grid emission factor determination',
      isAvailable: true,
      verificationStatus: 'VERIFIED'
    },
    {
      title: 'ASTM E1675',
      exactWording: 'ASTM Standard Practice E1675 for Sampling 2-Phase Geothermal Fluid for Purposes of Chemical Analysis',
      section: '5.1, Data table 10',
      page: 24,
      paragraph: '68',
      impact: 'Sampling and analysis of geothermal non-condensable gases',
      isAvailable: true,
      verificationStatus: 'VERIFIED'
    }
  ],
  applicabilityConditions: [
    {
      id: 'en01-001-cond-1',
      field: 'grid_connected',
      label: 'Grid-Connected Renewable Generation',
      operator: 'EQUALS',
      expectedValue: true,
      isMandatory: true,
      pageReference: 5,
      sectionReference: '3.1, paragraph 6',
      provenanceQuote: 'This methodology applies to grid-connected renewable energy generation project activities that include: (a) Construction and operation of a Greenfield power plant; or (b) Retrofitting, rehabilitation, replacement or capacity addition of an existing power plant.',
      failureMessage: 'The project must be connected to the electricity grid.'
    },
    {
      id: 'en01-001-cond-2',
      field: 'not_fossil_fuel_switch',
      label: 'Exclusion of On-Site Fossil Fuel Switch',
      operator: 'EQUALS',
      expectedValue: true,
      isMandatory: true,
      pageReference: 8,
      sectionReference: '3.2, paragraph 15(a)',
      provenanceQuote: 'The methodology is not applicable to: (a) Project activities that involve switching from fossil fuels to renewable energy sources at the site of the project activity, since in this case the baseline may be the continued use of fossil fuels at the site;',
      failureMessage: 'Projects involving on-site switching from fossil fuels to renewable sources are not eligible under BM EN01.001.'
    },
    {
      id: 'en01-001-cond-3',
      field: 'not_biomass_fired',
      label: 'Exclusion of Biomass Fired Plants',
      operator: 'EQUALS',
      expectedValue: true,
      isMandatory: true,
      pageReference: 8,
      sectionReference: '3.2, paragraph 15(b)',
      provenanceQuote: 'The methodology is not applicable to: (b) Biomass fired power plants/units.',
      failureMessage: 'Biomass fired plants must use BM EN01.003 instead of BM EN01.001.'
    },
    {
      id: 'en01-001-cond-4',
      field: 'bess_grid_charging_limit',
      label: 'BESS Grid Charging Limit (<= 2%)',
      operator: 'LESS_THAN',
      expectedValue: 2.0,
      unit: '%',
      isMandatory: false,
      pageReference: 7,
      sectionReference: '3.2, paragraph 11(d)',
      provenanceQuote: 'The charging using the grid or using fossil fuel electricity generator should not amount to more than 2 per cent of the electricity generated by the project renewable energy plant during a monitoring period.',
      failureMessage: 'BESS charging from grid/fossil sources exceeds 2% threshold during the monitoring period.'
    }
  ],
  monitoringRequirements: [
    {
      id: 'en01-001-mon-1',
      parameter: 'Quantity of net electricity generation supplied to grid',
      parameterSymbol: 'EGPJ,y / EGfacility,y',
      unit: 'MWh/year',
      frequency: 'CONTINUOUS',
      equipment: 'Calibrated electricity meters',
      standard: 'National / International metering standards',
      pageReference: 26,
      sectionReference: '5.1, Data Table 14',
      qaQcProcedure: 'Calibration records of the electricity meters to be maintained and archived; cross-checked with utility invoices.'
    },
    {
      id: 'en01-001-mon-2',
      parameter: 'Electricity consumed from grid for auxiliary/charging',
      parameterSymbol: 'Aux,y / ECBESS,y',
      unit: 'MWh/year',
      frequency: 'CONTINUOUS',
      equipment: 'Calibrated electricity meters',
      standard: 'BM-T-003',
      pageReference: 26,
      sectionReference: '5.1, Data Table 15'
    }
  ],
  evidenceRequirements: [
    {
      id: 'en01-001-ev-1',
      documentType: 'POWER_PURCHASE_AGREEMENT',
      description: 'Grid connection agreement and Power Purchase Agreement (PPA) with state DISCOM or open access consumer',
      isMandatory: true,
      pageReference: 5,
      sectionReference: '3.1, paragraph 6',
      provenanceQuote: 'This methodology applies to grid-connected renewable energy generation project activities'
    },
    {
      id: 'en01-001-ev-2',
      documentType: 'COMMISSIONING_CERTIFICATE',
      description: 'Official commercial commissioning certificate and technical plant design specifications',
      isMandatory: true,
      pageReference: 20,
      sectionReference: '4.5.1.4, paragraph 59(b)(i)',
      provenanceQuote: 'The commissioning of the plant/unit; last capacity addition; or last retrofit/rehabilitation.'
    }
  ],
  calculationFormulas: [
    {
      formulaId: 'en01-001-eq-11',
      name: 'Baseline Emissions for Grid-Connected Renewable Electricity',
      equationText: 'BE_y = EG_PJ,y * EF_grid,CM,y',
      equationNumber: 'Equation (11)',
      section: '4.5, paragraph 49',
      page: 18,
      description: 'Calculates baseline emissions displaced by net electricity supplied to the grid by the renewable energy plant.',
      outputUnit: 't CO2/yr',
      requiredParameters: [
        {
          name: 'Net electricity generation supplied to grid',
          symbol: 'EG_PJ,y',
          unit: 'MWh/yr',
          description: 'Quantity of net electricity generation produced and supplied to the grid in year y',
          source: 'On-site calibrated electricity meters',
          isMonitored: true
        },
        {
          name: 'Combined Margin Grid Emission Factor',
          symbol: 'EF_grid,CM,y',
          unit: 't CO2/MWh',
          description: 'Grid Emission Factor (for net effective injection into grid) published by Central Electricity Authority (CEA)',
          source: 'CEA CO2 Baseline Database for the Indian Power Sector',
          isMonitored: false
        }
      ]
    },
    {
      formulaId: 'en01-001-eq-17',
      name: 'Emission Reductions',
      equationText: 'ER_y = BE_y - PE_y',
      equationNumber: 'Equation (17)',
      section: '4.7, paragraph 64',
      page: 21,
      description: 'Emission reductions achieved by the renewable energy project activity.',
      outputUnit: 't CO2e/yr',
      requiredParameters: [
        {
          name: 'Baseline Emissions',
          symbol: 'BE_y',
          unit: 't CO2/yr',
          description: 'Baseline emissions in year y',
          source: 'Equation (11)',
          isMonitored: false
        },
        {
          name: 'Project Emissions',
          symbol: 'PE_y',
          unit: 't CO2e/yr',
          description: 'Project emissions in year y (fossil backup, reservoir emissions, BESS charging emissions)',
          source: 'Equation (1)',
          isMonitored: false,
          defaultValue: 0
        }
      ]
    }
  ]
};
